// Deploy profile — auto-generated from personal-profile.js by scripts/prepare-deploy.sh
// Commit this file so GitHub Pages gets your meal/food catalog.
window.__PERSONAL__ = window.__PERSONAL__ || {};
window.__PERSONAL__.profile = {
  baseline: {
  date:'2026-06-13',
  weight:213.4, bodyFat:19.2, muscleMass:163.8, visceralFat:9,
  skeletalMuscle:52.1, fatFreeMass:172.4, subcutFat:16.6,
  bodyWater:58.3, boneMass:8.6, protein:18.4, bmr:2040, metabolicAge:25,
  note:'Starting point — Compared vs Dec 16 2025 baseline. Down 61lbs, -11.3% body fat, +7.4% skeletal muscle.'
},
  recompGoal: {targetBF:12,leanLossShare:0.15,startWeight:212.4,startBF:19.1,active:true},
  baseSchedule: {
  SUN:{mt:"CHEST",work:true,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"10:00 AM",l:"Wake up",type:"wake"},
    {t:"10:02 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"10:05 AM",l:"Supplements",type:"supps"},
    {t:"10:00 AM",l:"Brush Teeth",type:"brush"},
    {t:"10:20 AM",l:"Walk · 20 min",type:"walk",hidden:true},
    {t:"10:30 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"11:15 AM",l:"Morning Check-in",type:"journal"},
    {t:"11:25 AM",l:"Journal",type:"deepjournal"},
    {t:"12:15 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"12:30 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"1:00 PM",l:"Workout · Chest",type:"training",tl:"CHEST",sa:true},
    {t:"1:45 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"2:15 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"2:30 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:20 PM",l:"Brush Teeth",type:"brush"},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]},
  MON:{mt:"BACK",work:true,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"5:00 AM",l:"Drive home from work · 30 min",type:"drivehome"},
    {t:"5:30 AM",l:"Shift ends · Home",type:"workend"},
    {t:"5:45 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"5:35 AM",l:"Supplements",type:"supps"},
    {t:"5:45 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"6:20 AM",l:"Morning Check-in",type:"journal"},
    {t:"6:30 AM",l:"Journal",type:"deepjournal"},
    {t:"6:35 AM",l:"Trading",type:"trade"},
    {t:"5:30 AM",l:"Brush Teeth",type:"brush"},
    {t:"9:00 AM",l:"Sleep",type:"sleep",tEnd:"3:00 PM"},
    {t:"3:05 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"3:15 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"3:45 PM",l:"Workout · Back",type:"training",tl:"BACK",sa:true},
    {t:"4:30 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"5:00 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"5:15 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:45 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:20 PM",l:"Brush Teeth",type:"brush"},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]},
  TUE:{mt:"LEGS",work:true,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"5:00 AM",l:"Drive home from work · 30 min",type:"drivehome"},
    {t:"5:30 AM",l:"Shift ends · Home",type:"workend"},
    {t:"5:45 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"5:35 AM",l:"Supplements",type:"supps"},
    {t:"5:45 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"6:20 AM",l:"Morning Check-in",type:"journal"},
    {t:"6:30 AM",l:"Journal",type:"deepjournal"},
    {t:"6:35 AM",l:"Trading",type:"trade"},
    {t:"5:30 AM",l:"Brush Teeth",type:"brush"},
    {t:"9:00 AM",l:"Sleep",type:"sleep",tEnd:"3:00 PM"},
    {t:"3:05 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"3:15 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"3:45 PM",l:"Workout · Legs",type:"training",tl:"LEGS",sa:true},
    {t:"4:30 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"5:00 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"5:15 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:45 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:20 PM",l:"Brush Teeth",type:"brush"},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]},
  WED:{mt:"ABS",work:true,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"5:00 AM",l:"Drive home from work · 30 min",type:"drivehome"},
    {t:"5:30 AM",l:"Shift ends · Home",type:"workend"},
    {t:"5:45 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"5:35 AM",l:"Supplements",type:"supps"},
    {t:"5:45 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"6:20 AM",l:"Morning Check-in",type:"journal"},
    {t:"6:30 AM",l:"Journal",type:"deepjournal"},
    {t:"6:35 AM",l:"Trading",type:"trade"},
    {t:"5:30 AM",l:"Brush Teeth",type:"brush"},
    {t:"9:00 AM",l:"Sleep",type:"sleep",tEnd:"3:00 PM"},
    {t:"3:05 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"3:15 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"3:45 PM",l:"Workout · Abs",type:"training",tl:"ABS",sa:true,cardio:true},
    {t:"4:30 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"5:00 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein"},
    {t:"5:15 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:45 PM",l:"Meal 3 · Bare Chicken · 4 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:20 PM",l:"Brush Teeth",type:"brush"},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]},
  THU:{mt:"ARMS",work:true,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"5:00 AM",l:"Drive home from work · 30 min",type:"drivehome"},
    {t:"5:30 AM",l:"Shift ends · Home",type:"workend"},
    {t:"5:45 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"5:35 AM",l:"Supplements",type:"supps"},
    {t:"5:45 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"6:20 AM",l:"Morning Check-in",type:"journal"},
    {t:"6:30 AM",l:"Journal",type:"deepjournal"},
    {t:"6:35 AM",l:"Trading",type:"trade"},
    {t:"5:30 AM",l:"Brush Teeth",type:"brush"},
    {t:"9:00 AM",l:"Sleep",type:"sleep",tEnd:"3:00 PM"},
    {t:"3:05 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"3:15 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"3:45 PM",l:"Workout · Shoulders + Arms",type:"training",tl:"ARMS",sa:true},
    {t:"4:30 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"5:00 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"5:15 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:45 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:20 PM",l:"Brush Teeth",type:"brush"},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]},
  FRI:{mt:"CHESTBACK",work:false,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"5:00 AM",l:"Drive home from work · 30 min",type:"drivehome"},
    {t:"5:30 AM",l:"Shift ends · Home",type:"workend"},
    {t:"5:45 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"5:35 AM",l:"Supplements",type:"supps"},
    {t:"5:45 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"6:20 AM",l:"Morning Check-in",type:"journal"},
    {t:"6:30 AM",l:"Journal",type:"deepjournal"},
    {t:"6:35 AM",l:"Trading",type:"trade"},
    {t:"5:30 AM",l:"Brush Teeth",type:"brush"},
    {t:"9:00 AM",l:"Sleep",type:"sleep",tEnd:"1:00 PM"},
    {t:"1:15 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"1:30 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"2:00 PM",l:"Workout · Chest + Back",type:"training",tl:"CHEST + BACK",sa:true},
    {t:"2:45 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"3:15 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"3:30 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:30 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:30 PM",l:"Brush Teeth",type:"brush"}
  ]},
  SAT:{mt:"ABS",work:false,blocks:[
    {t:"12:00 AM",l:"Caffeine",type:"caffeine"},
    {t:"10:00 AM",l:"Wake up",type:"wake"},
    {t:"10:02 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"10:05 AM",l:"Supplements",type:"supps"},
    {t:"10:00 AM",l:"Brush Teeth",type:"brush"},
    {t:"10:20 AM",l:"Walk · 20 min",type:"walk",hidden:true},
    {t:"10:30 AM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"11:15 AM",l:"Morning Check-in",type:"journal"},
    {t:"11:25 AM",l:"Journal",type:"deepjournal"},
    {t:"12:15 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops — pre-workout",type:"dextrose",scoops:2}]},
    {t:"12:30 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"1:00 PM",l:"Workout · Abs",type:"training",tl:"ABS",sa:true,cardio:true},
    {t:"1:45 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"2:15 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein"},
    {t:"2:30 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:30 PM",l:"Meal 3 · Bare Chicken · 4 pcs",type:"meal",ms:"m3"},
    {t:"8:00 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:30 PM",l:"Brush Teeth",type:"brush"}
  ]}
},
  mealMacrosTraining: {CHEST:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  BACK:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  LEGS:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  ARMS:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  CHESTBACK:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  // Optional arm split — same training macros as ARMS by default
  TRICEPS:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  BICEPS:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},
  SHOULDERS:{kcal:2560,P:248,C:226,F:85,totalShakes:3,
    m1:{P:28,C:90,F:30,kcal:740,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:4,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:64,C:40,F:20,kcal:600,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:8,step:1}]},
    dextrose:{scoops:4,C:72,kcal:280}},

  // REST/ABS: 1cup pancake+6bacon | 2tort+1cup mozz | 4pcs chicken | 8sc shake | 2sc dex
  // ACTUAL:   P:226  C:170  F:89  2280kcal
  ABS:{kcal:2280,P:226,C:170,F:89,totalShakes:3,
    m1:{P:38,C:90,F:44,kcal:900,items:[{n:"Costco Pancake Mix",a:"½ cup per serving",defaultSv:2,step:1},{n:"Costco Bacon",a:"1 slice (13g)",defaultSv:6,step:1}]},
    m2:{P:36,C:12,F:31,kcal:460,items:[{n:"Mission Carb Balance Tortilla",a:"1 tortilla (43g)",defaultSv:2,step:1},{n:"Lucerne Mozzarella Shredded",a:"½ cup per tortilla (4×¼ cup)",defaultSv:4,step:1}]},
    m3:{P:32,C:20,F:10,kcal:300,items:[{n:"Just Bare Chicken Strips",a:"2 pieces (85g) per serving",defaultSv:4,step:1}]},
    dextrose:{scoops:2,C:36,kcal:140}}},
  soccerSchedule: {
  // Each entry is the FULL block array for that Sunday (replaces recurring schedule)
  '2026-06-21':[
    {t:"7:45 AM",l:"Wake up",type:"wake"},
    {t:"7:47 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"7:47 AM",l:"Take supplements",type:"supps"},
    {t:"7:45 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:00 AM",l:"Morning Check-in",type:"journal"},
    {t:"8:10 AM",l:"Journal",type:"deepjournal"},
    {t:"8:45 AM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"9:30 AM",tEnd:"11:15 AM",l:"vs Anatolia United",type:"soccer",loc:"Genesee Upper Playfield"},
    {t:"11:15 AM",l:"Drive home · 40 min",type:"travelback"},
    {t:"12:10 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"1:10 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"1:40 PM",l:"Workout",type:"training",tl:"CHEST",sa:true},
    {t:"2:55 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"3:25 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"3:40 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ],
  '2026-06-28':[
    {t:"9:00 AM",l:"Wake up",type:"wake"},
    {t:"9:02 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"9:02 AM",l:"Take supplements",type:"supps"},
    {t:"9:00 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"9:15 AM",l:"Morning Check-in",type:"journal"},
    {t:"9:25 AM",l:"Journal",type:"deepjournal"},
    {t:"10:00 AM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"10:45 AM",tEnd:"12:30 PM",l:"Home · Strangers United FC",type:"soccer",loc:"Lower Woodland Park · Field 2"},
    {t:"12:30 PM",l:"Drive home · 40 min",type:"travelback"},
    {t:"1:25 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"2:25 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"2:55 PM",l:"Workout",type:"training",tl:"CHEST",sa:true},
    {t:"4:10 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"4:40 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"4:55 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ],
  '2026-07-12':[
    {t:"7:45 AM",l:"Wake up",type:"wake"},
    {t:"7:47 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"7:47 AM",l:"Take supplements",type:"supps"},
    {t:"7:45 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:00 AM",l:"Morning Check-in",type:"journal"},
    {t:"8:10 AM",l:"Journal",type:"deepjournal"},
    {t:"8:45 AM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"9:30 AM",tEnd:"11:15 AM",l:"Away · Strangers United FC",type:"soccer",loc:"Genesee Lower Playfield"},
    {t:"11:15 AM",l:"Drive home · 40 min",type:"travelback"},
    {t:"12:10 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"1:10 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"1:40 PM",l:"Workout",type:"training",tl:"CHEST",sa:true},
    {t:"2:55 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"3:25 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"3:40 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ],
  '2026-07-19':[
    {t:"9:30 AM",l:"Wake up",type:"wake"},
    {t:"9:32 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"9:32 AM",l:"Take supplements",type:"supps"},
    {t:"9:30 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"9:45 AM",l:"Morning Check-in",type:"journal"},
    {t:"9:55 AM",l:"Journal",type:"deepjournal"},
    {t:"10:30 AM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"11:15 AM",tEnd:"1:00 PM",l:"vs Goon Squad FC",type:"soccer",loc:"Magnuson Park · Field 6"},
    {t:"1:00 PM",l:"Drive home · 40 min",type:"travelback"},
    {t:"1:55 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"2:55 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"3:25 PM",l:"Workout",type:"training",tl:"CHEST",sa:true},
    {t:"4:40 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"5:10 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"5:25 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ],
  '2026-07-26':[
    {t:"7:45 AM",l:"Wake up",type:"wake"},
    {t:"7:47 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"7:47 AM",l:"Take supplements",type:"supps"},
    {t:"7:45 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:00 AM",l:"Morning Check-in",type:"journal"},
    {t:"8:10 AM",l:"Journal",type:"deepjournal"},
    {t:"8:45 AM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"9:30 AM",tEnd:"11:15 AM",l:"Away · Strangers United FC",type:"soccer",loc:"Loyal Heights Playfield"},
    {t:"11:15 AM",l:"Drive home · 40 min",type:"travelback"},
    {t:"12:10 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"1:10 PM",l:"Drive to gym · 30 min",type:"travel"},
    {t:"1:40 PM",l:"Workout",type:"training",tl:"CHEST",sa:true},
    {t:"2:55 PM",l:"Drive home from gym · 30 min",type:"travelback"},
    {t:"3:25 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"3:40 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ],
  '2026-08-02':[
    {t:"11:15 AM",l:"Wake up",type:"wake"},
    {t:"11:17 AM",type:"shake",scoops:4,idx:1,tot:3,l:"Shake 1 · 60g protein"},
    {t:"11:17 AM",l:"Take supplements",type:"supps"},
    {t:"11:15 AM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"11:30 AM",l:"Morning Check-in",type:"journal"},
    {t:"11:40 AM",l:"Journal",type:"deepjournal"},
    {t:"12:15 PM",l:"Drive to Soccer · 45 min",type:"travel"},
    {t:"1:00 PM",tEnd:"2:45 PM",l:"vs Bob Esponja (Red)",type:"soccer",loc:"Magnuson Park · Field 7"},
    {t:"2:45 PM",l:"Drive home · 40 min",type:"travelback"},
    {t:"3:40 PM",l:"Meal 1 · Pancakes + Bacon",type:"meal",ms:"m1"},
    {t:"3:55 PM",type:"shake",scoops:2,idx:2,tot:3,l:"Shake 2 · 30g protein",sub:[{l:"Dextrose · 2 scoops",type:"dextrose",scoops:2}]},
    {t:"4:10 PM",l:"Meal 2 · Tortillas + Mozzarella",type:"meal",ms:"m2"},
    {t:"7:00 PM",l:"Meal 3 · Bare Chicken · 8 pcs",type:"meal",ms:"m3"},
    {t:"7:45 PM",l:"Evening Check-in",type:"journal"},
    {t:"8:00 PM",l:"Brush Teeth · 5 min",type:"brush"},
    {t:"8:10 PM",type:"shake",scoops:2,idx:3,tot:3,l:"Shake 3 · 30g protein",sub:[{l:"Dextrose · 2 scoops — post-workout",type:"dextrose",scoops:2}]},
    {t:"8:30 PM",l:"Drive to work · 30 min",type:"drivework"},
    {t:"9:00 PM",l:"Shift start",type:"work"}
  ]
},
  mealPlannerFoods: [
  {id:'pancake', name:'Costco Pancake Mix',   unit:'½ cup',    unitPer:1, label:'½ cups', P:4,  C:45, F:1,  kcal:210, category:'food'},
  {id:'bacon',   name:'Costco Bacon',         unit:'slice',    unitPer:1, label:'slices', P:5,  C:0,  F:7,  kcal:80, category:'food'},
  {id:'tortilla',name:'Mission Carb Balance Tortilla', unit:'tortilla', unitPer:1, label:'tortillas', P:6, C:2, F:3.5, kcal:70, category:'food'},
  {id:'mozz',    name:'Lucerne Mozzarella Shredded', unit:'¼ cup', unitPer:1, label:'¼ cups', P:6, C:2, F:6, kcal:80, category:'food'},
  {id:'chicken', name:'Just Bare Chicken Strips', unit:'piece', unitPer:1, label:'pieces', P:8, C:5, F:2.5, kcal:75, category:'food'},
  {id:'protein', name:'Premier Protein Whey', unit:'scoop',    unitPer:1, label:'scoops', P:15, C:1.5, F:0.5, kcal:60, category:'powder'},
  {id:'dextrose',name:'Dextrose',             unit:'scoop',    unitPer:1, label:'scoops', P:0,  C:18, F:0,  kcal:70, category:'powder'},
],
  mealPresets: [
    {name:'Pancakes + Bacon', items:[{id:'pancake',sv:4},{id:'bacon',sv:4}]},
    {name:'Quesadilla',       items:[{id:'tortilla',sv:2},{id:'mozz',sv:4},{id:'dextrose',sv:3}]},
    {name:'Post-gym Shake',   items:[{id:'protein',sv:2},{id:'dextrose',sv:2}]},
    {name:'Bare Chicken Bowl',items:[{id:'chicken',sv:2},{id:'tortilla',sv:2},{id:'mozz',sv:2}]},
  ],
  brandStripWords: ['Costco','Mission','Lucerne','Just','Carb','Balance'],
  postFastProteinFoodId: 'chicken',
  tradeFirms: ['Tradeify','Lucid','Topstep'],
  proteinDrinks: [
  {id:'default',name:'Premier Protein Whey',P:15,C:1.5,F:0.5,kcal:60,defaultServings:2},
  {id:'c4_25g',name:'C4 25g Protein',P:25,C:2,F:1,kcal:120,defaultServings:1},
],
  drinkColorFixed: {c4_25g:1},
  supplementTypes: [
    {id:'sp_creatine',name:'Creatine',category:'powder',form:'scoop',doseAmount:5,doseUnit:'g',pillCount:1,servingsPerContainer:200,inStock:true,timing:'post_workout'},
    {id:'sp_collagen',name:'Collagen',category:'powder',form:'scoop',doseAmount:20,doseUnit:'g',pillCount:1,servingsPerContainer:28,inStock:true,timing:null},
    {id:'sp_dextrose',name:'Dextrose',category:'powder',form:'scoop',doseAmount:20,doseUnit:'g',pillCount:1,servingsPerContainer:227,inStock:true,timing:'post_workout'},
    {id:'sp_vitd',name:'Vitamin D3 + K2',category:'pill',form:'capsule',doseAmount:125,doseUnit:'mcg',pillCount:2,servingsPerContainer:60,inStock:true,timing:'am'},
    {id:'sp_fishoil',name:'Fish Oil',category:'pill',form:'softgel',doseAmount:1200,doseUnit:'mg',pillCount:2,servingsPerContainer:67,inStock:true,timing:'with_meal'},
    {id:'sp_magglycinate',name:'Magnesium Glycinate',category:'pill',form:'capsule',doseAmount:100,doseUnit:'mg',pillCount:2,servingsPerContainer:30,inStock:true,timing:'before_sleep'},
    {id:'sp_ltyrosine',name:'L-Tyrosine',category:'pill',form:'tablet',doseAmount:500,doseUnit:'mg',pillCount:1,servingsPerContainer:100,inStock:true,timing:'am'},
    {id:'sp_multivitamin',name:'Multivitamin',category:'pill',form:'capsule',doseAmount:null,doseUnit:null,pillCount:1,servingsPerContainer:null,inStock:false,timing:null},
    {id:'sp_magnesium',name:'Magnesium',category:'pill',form:'capsule',doseAmount:null,doseUnit:null,pillCount:1,servingsPerContainer:null,inStock:false,timing:null},
    {id:'sp_ashwagandha',name:'Ashwagandha',category:'pill',form:'capsule',doseAmount:null,doseUnit:null,pillCount:1,servingsPerContainer:null,inStock:false,timing:null},
    {id:'sp_wellbutrin',name:'Wellbutrin',category:'pill',form:'tablet',doseAmount:null,doseUnit:null,pillCount:1,servingsPerContainer:null,inStock:false,timing:null},
  ],
  exerciseLibrary: {
  CHEST:['Cable Chest Fly','Underhand Cable Chest Fly','Pec Deck','Smith Chest Press','Smith Incline Chest Press','Dumbbell Press','Dumbbell Incline Chest Press','Push-Ups','Machine Chest Press','Isometric Plate Loaded Chest Press'],
  BACK:['Lat Pulldown','Cable Lat Pullover','Face Pulls','Seated Cable Row','Assisted Pull-Ups','Cable Lat Pulldown - Single Arm','Cable Rear Delt Fly','Machine Rear Delt Fly','Dumbbell Lat Pullover','Back Extensions'],
  LEGS:['Hamstring Curl','Leg Extensions - Quads','Leg Press','Hip Adduction - Close','Hip Abduction - Open'],
  ABS:['Kneeling Cable Crunch','Ab Crunch Machine','Leg Raises','Cable Woodchop'],
  ARMS:[],
  TRICEPS:['Single-Arm Tricep Pushdown','Rope Tricep Pushdown','Straight-Bar Tricep Pushdown','Assisted Dips'],
  BICEPS:['Cable Bicep Curl','Single-Arm Cable Curl','Reverse Cable Curl','Rope Hammer Curl','EZ-Bar Curl','Dumbbell Curl','Forearm Curl','Preacher Curl','Machine Preacher Curl','EZ-Bar Spider Curl'],
  SHOULDERS:['Cable Lateral Raise','Dumbbell Lateral Raise','Dumbbell Shoulder Press','Dumbbell Overhead Press'],
},
  defaultTodoItems: [
    {id:'td_water',label:'16oz water upon waking',category:'routine',priority:'normal'},
    {id:'td_supps',label:'Take daily supplements',category:'routine',priority:'normal'},
    {id:'td_charts',label:'Prep daily charts & market levels',category:'work_trading',priority:'focus'},
    {id:'td_stretch',label:'10 min mobility & stretching',category:'fitness',priority:'normal'},
    {id:'td_read',label:'Read 15 min or review journal',category:'personal',priority:'normal'},
  ],
  taskCategories: [],
};
